### ISSUE TITLE
Setup of light platform wiz_light is taking over 10 seconds.

### ISSUE THREAD

**Issue by mlhomeboy** [sbidy/wiz_light#113]
I seem to get this error; the bulbs never connect.

**Comment by sbidy** [comment]
I'm working on that.
If the bulb is offline at startup, HASS will never bring the bulb in the state available. Regardless if the bulb is switched on after startup. Currently the workaround is to connect all bulb to power on startup.

It seems to be an issue with the HASS core because my integration will report the correct state in the `available` property. But if the bulb is offline at startup HASS flags this as "removed".

**Comment by mlhomeboy** [comment]
So I should make sure the bulbs are powered on then restart HASS?

**Comment by sbidy** [comment]
Yes - if it is not possible you can switch the bulb from `enable `to `disable `and back. You can find this switch via Settings (in the bulb card the ⚙️ symbol in the upper left corner).

**Comment by mlhomeboy** [comment]
Just tried no luck, unless i set this up wrong.

Also I see no Gear in the bulb card, but under a bulbs entity I have this message.

**This entity ("light.wiz_e6abf2") does not have a unique ID, therefore its settings cannot be managed from the UI. See the documentation for more detail. 

You can overwrite some attributes in the entity customizations section.**

Is this maybe my issue?

Thanks

**Comment by sbidy** [comment]
Do you add the bulb via UI or YAML file? If you add the bulb via YAML you should add the the `uniqe_id` property.
If you added the bulb via UI, please delete the bulb (device and entity) ad re-add it.

**Comment by bdraco** [comment]
This can be closed as its fixed in the core version
