### ISSUE TITLE
Feature: use one integration for all devices

### ISSUE THREAD

**Issue by excalbian** [sbidy/wiz_light#119]
Currently (unless I've missed something) this integration creates a new instance for each device, and I'm not sure how that will scale (my home has about a dozen Wiz bulbs).

<img width="267" alt="image" src="https://user-images.githubusercontent.com/242196/108634511-720abc80-743f-11eb-9b34-8d15d6af9606.png">

Would it be possible to do something similar to the Tasmota integration, which lists all the devices (and entities) under one instance of the integration?

<img width="265" alt="image" src="https://user-images.githubusercontent.com/242196/108634501-615a4680-743f-11eb-896c-e3c2dacf629c.png">

I'm quite rusty with Python, and haven't created an integration for Home Assistant before (or the config flow!!) but I'd be happy to help if there is anything I can do.

**Comment by spencerthayer** [comment]
Yikes, I didn't realize I would have to integrate each Wiz light.

**Comment by sbidy** [comment]
You need for every bulb a separate device and entry. Tasmota is MQTT based and one ESP can handle multiple types (multiple bulbs or sensors) in on device. From a scale set perspective HASS should handle up to 100 devices per integration. But this can be become a performance issue because of the UDP connections (see "Background" below).
To control every bulb separately you have to integrated everyone as device (for automation) and entry (for the overall control).
That is an requirement from the HASS platform, But I already implemented a discovery function to bring in a auto-detection to avoid a annoying manual adding of the devices (like for Tasmota and MQTT).

**Background:**
This integration is based on UDP and handles all connections and interactions directly from the HASS. The idea hind that is to avoid having a "gateway" or other "handler" (like the HUE GW or MQTT broker) between HASS and the device. Most of the integration out there (like HUE or IKEA) are using a gateway between HASS and the bulbs. This makes it overall easier to integrate these types of platforms (mostly they using MQTT or REST-APIs).

**Comment by code-in-progress** [comment]
> Currently (unless I've missed something) this integration creates a new instance for each device, and I'm not sure how that will scale (my home has about a dozen Wiz bulbs).

As someone with close to 50 bulbs, I can say firsthand that it was a PAIN to setup. I LOVE this project, but for the integration to work 100% for me, it has to support auto-discovery. 

@sbidy To your point about UDP performance, yeah, I wouldn't recommend running over 10-20 bulbs on a consumer router... ever. Fortunately, I have a Unifi setup, so I don't have many issues with multicast performance (aside from the typical Unifi issues).

**Comment by excalbian** [comment]
> But I already implemented a discovery function to bring in a auto-detection to avoid a annoying manual adding of the devices (like for Tasmota and MQTT).

Is there a way that I can test this auto-detection? I read (and re-read) your answer and am worried that we're talking about two different things, but possibly it's also just my own ignorance, so I'd be happy to test and then provide more feedback.

Like @code-in-progress mentioned, I LOVE this project and am so grateful for having it. Being able to use these (cheaper) smart bulbs without a hub device in my home automation is perfect.

**Comment by sbidy** [comment]
Ah - sorry for my confusing answer 😉
To be more precisely: The auto-discover feature is currently not available in the integration. It is part of the underlining library (pywizlight). But I'm looking forward to bring this in the next version of the wiz_light integration.

The problem with an entry+device for each bulb will stay and will not be change in the future.

**Comment by spencerthayer** [comment]
@sbidy do you have a rough timeline when y'all might start working on auto-discovery?

**Comment by sbidy** [comment]
Currently I'm fixing the startup issue (bulbs are stucking offline after reboot).
But I'm looking forward to bring this in the next version as  Beata feature. The implementation in the backend is there - only the HASS part is missing.

**Comment by splerman** [comment]
First, I have to say that if weren't for sbidy and wiz_light, I never would have embarked down the Home Assistant path. After picking up 4 Hue bulbs, lamenting the cost and then finding that WiZ bulbs had nearly the same color quality at 25% of the cost... wiz_light was stable enough on v0.2 that I replaced nearly every bulb in the house (garage flourescent and a couple odd-ball art lights are all that's left). 98 bulbs, 70+ Z-Wave Dimmers later...

98 Wiz Bulbs here. I've been running wiz_light v0.2 since December. I tried going to 0.4 for a hot-minute, but getting every bulb available for every restart killed me in less than 24 hours. I was so very happy to revert back to my yaml configuration (I use an Excel spreadsheet of my bulb inventory and it auto-generates my wiz_light yaml and my pi-hole A-records. If only the Unifi Controller could import fixed IP reservations or provided a straight-forward API...

With 98 bulbs, the current GUI-based registration is a non-starter. Also, there is currently no way to change an IP address or IP hostname without deleting the bub and re-adding it. Doesn't sound bad until you have to scroll through 98 bulbs to find each one individually...and you have to change 5 bulbs. Some kind of control panel (like zwavejsmqtt or the legacy zwave integration is very  much needed. Also, need to figure out how to do default light profiles since light_profiles.csv doesn't allow "effects". If I simply set the bulb to the color code equivalent of Daylight, it is dramatically dimmer than if I enable the effect Daylight.

My setup is 82 Color BR30s, 14, Color A19s and 2 Color A21s. They're all driven by Zooz ZEN22 Z-Wave Dimmers in Smart Bulb mode (i.e., local load control disabled). 1x Tap On turns on to last setting (from off); 1x Tap On increments through a list of colors and/or effects (if already on). 2x Tap On turns on to Daylight 100%. 1x Tap Off turns Off (if On). 1x Tap Off turns on Night Light mode at 20% (if Off). Triple Tap does various things depending upon the switch and the "target_light_group".

**Comment by spencerthayer** [comment]
> 98 Wiz Bulbs here.

‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️😳‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️

I have questions. Does registering 98 bulbs via YAML work efficiently? Doesn't the GUI do a better job at generating UUIDs? How do you remove an integration? What is the effect on your network with that much traffic?

**Comment by sbidy** [comment]
I'm still working on it and looking forward to release a first beta of the 0.5 version.
It should be possible that the integration will auto-detect reachable bulbs via UDP broadcast.

**Some words to the network traffic:** This integration is one of a small number which handles the interaction with the devices directly in HASS. The most other platforms are using broker, gateways or proxies to interact with the  IoT device. Like HUE, MQTT or other. To use a broker (e.g. MQTT) makes it little bit more scalable.
To accomplish this we use in the backed lib a highly async call stack to make this integration as fast and stable as possible. At the end we send some UDP packages to the bulb, In case of 100 bulbs this should be fast and stable enough but you will see some more UDP packages in the network. These packages are relay small and should not be a problem in the "normal" Netflix-Scaled-Home-WiFi 😄 .

**Some words to the YAML config:** I'm a big fan of configuring my HASS with this file too. But unfortunately the HASS core team are marked this as deprecated and will be removed from future versions. I don't know exactly why this change was made but for adding >10 devices via UI without an auto-detection can become a horror.

**Comment by splerman** [comment]
> > 98 Wiz Bulbs here.
> 
> ‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️😳‼️‼️‼️‼️‼️‼️‼️‼️‼️‼️
> 
> I have questions. Does registering 98 bulbs via YAML work efficiently?

Absolutely. I have an Excel spreadsheet that I use for device inventory and IP address management (of my IoT subnet only). This spreadsheet automates my light config, my light group config, my PiHole Local DNS records config, etc. I also read it into a Global array in Node Red where it will be used for additional things 
like tracking unavailable devices etc. A sample of my auto-gen’d config, below.

  # WiZ BR30 Color
  # Hostname: bathroom-shower.mydomain.com
  # IP Address: 10.101.8.72
  # MAC Address:a8:bb:50:7c:31:XX
  - platform: wiz_light
    name: Bathroom Shower
    host: 10.101.8.72
  # WiZ BR30 Color
  # Hostname: bathroom-tub.mydomain.com
  # IP Address: 10.101.8.73
  # MAC Address:a8:bb:50:7c:2d:XX
  - platform: wiz_light
    name: Bathroom Tub
    host: 10.101.8.73

Doesn't the GUI do a better job at generating UUIDs?

IMHO, GUIs are intended for ease of use, not efficiency. They make it easy to accomplish tasks that you do infrequently and don’t remember syntax etc. If I need to do something repetitive, I want to automate it. GUIs are hard to automate. Anything text/keyboard based can be scripted easily.

How do you remove an integration?
For me, YAML is much more flexible in allowing me to disable/remove integrations than the GUI. Since I’m newer to HA and still “tinkering”, I spend a lot of time trying different ways of accomplishing a specific task. Thus, I’m often “temporarily” disabling things to try alternatives. With YAML, I comment out an integration and reboot. The key thing for me is that I still have a record of the config and can re-add it by removing the #s. With the GUI, I have to document how an integration is configured before I remove it so I can re-add it later.

What is the effect on your network with that much traffic?
My network is all Unifi gear. I’ve got 3 AC-M Access Points, 5 8-port 1Gig access switches, a 24-port core switch and a USG-3P for routing/access etc. My IoT devices have been transitioned to their own SSID and subnet. So far, my network performance hasn’t degraded at all. I’m also really impressed by how responsive the lights are given that I’m controlling them via Zwave switches, ZwaveJS2MQTT, Node Red and HA. Node Red listens for zwavejs events. When one comes in, it traverses an array of zwave devices to find the matching node_id. It also determines the target device(s) from a matrix of mappings. A function node interprets the scene data to derive the user action and, based upon the current state of the target and user action, derives a service call and service data.

One of the best things the setup has accomplished is freeing me from my home’s hard wiring. We have an insane number of light switches that aren’t always in the best locations for the things they control. We also can never remember which switch controls which lights (I’d like to shoot the guy that thought 6-gang switches were a good idea). With this setup, I’ve freed myself to redefine light groups, and minimize the number of switches actually necessary based on our typical usage and then assign light groups to the switch that we find most intuitive.

Hope this addressed your questions. Happy to provide any further info.

**Comment by spencerthayer** [comment]
@splerman do you ever experience anything like [this issue I am having](https://github.com/sbidy/wiz_light/issues/129)?

**Comment by bdraco** [comment]
This can be closed as its not as we want a config entry per device so we can use the internal Home Assistant tooling and auto discovery to manage entries and report why devices are having trouble.  Its kinda moot now that discovery is implemented in the core version anyways
