### ISSUE TITLE
Unable to edit entities from UI

### ISSUE THREAD

**Issue by chansearrington** [sbidy/wiz_light#192]
When viewing the entity in Home Assistant front end,

I'm unable to edit the entity.

I'm just trying to rename the entity. (see image)

![image](https://user-images.githubusercontent.com/123082/138572575-bf12078a-5fd6-47c0-bbcd-b19e1af7f0d4.png)

**Comment by DrewGilbey** [comment]
I have the same issue while trying to make changes. All lights added via Configurations, Integrations, + integration, search WIZ, add via IP address.

I added all my lights like this. I made changed to IP assignments. In order to make changed I deleted the entities from the wiz inaugurations but they are stores somewhere still. It won't let me re add the lights with different IP. When I look at the entities list I still find the deleted lights and they are labeled read-only. 

 
![Screen Shot 2021-11-09 at 12 00 44 PM](https://user-images.githubusercontent.com/83251034/140970705-4f6500e4-d1f7-439f-b1fd-b805a8371fa1.png)

**Comment by sbidy** [comment]
If tested the scene feature with the integration, and it worked as expected. In case of IP address changes (expired leastimes) there can reside some "zombie" entries.

1.  Please delete all bulbs (devices and entries)
2. Ensure that you are using the latest version of the wiz_light integration
2. Restart HASS - Keep in mind that all bulbs should be connected to the power while restarting HASS
3. Re-Add the bulbs with the DNS name `wiz-<last 6 digits from the MAC>` - you can find the MAC in the WiZ app by hitting in the settings on the "Model" text. This will prevent an issue in case of an IP address change.
4. The bulbs should be added as device and entry

Hope this helps....

**Comment by spencerthayer** [comment]
@sbidy can you provide an example of this for the yaml?

**Comment by sbidy** [comment]
I learned that the YAML will be deprecated in the future and should not be used anymore.
Because of that, not all "new" or current features will be supported with newer HASS versions.

If you have issues with the entries, devices, scenes, or automations, please consider fist to re-add the bulb with the UI Wizard.
This can be a hassle if you have multiple bulbs. We are working (in the official PR for HASS core) currently on an auto discovery solution.

As I mentioned above, you should add the bulbs with the DNS name. But this prerequisite, a working DNS resolution.
I added my bubs with `wiz-AABBCC` via UI Wizard.

**Comment by spencerthayer** [comment]
Tried reinstalling all of my lights using the wiz underscore last six characters of the mac address convention. In the example below the entity ID is wiz_d336f6 which matches the name of the light with my router. Still I am getting _2 error. The Hass version info is core-2021.12.0.

<img width="1108" alt="Screen Shot 2021-12-12 at 3 09 13 PM" src="https://user-images.githubusercontent.com/1019815/145733369-87d9e642-af21-4ecf-9240-35d12d2459ad.png">

**Comment by bdraco** [comment]
This can be closed as its implemented in the core version
