### ISSUE TITLE
Support Speed option for effects

### ISSUE THREAD

**Issue by quielb** [sbidy/wiz_light#218]
Several of the effects has a speed option. Please add support for the speed capability in the HA component. The turn_on service does not support a speed attribute. You may consider creating a custom service like `effect` similar to how the WLED integration handles the speed option with the service `wled.effect`

**Comment by trancefam** [comment]
This would be cool if it was possible through the api (I do not know). I did want to mention though that the `wled.effect` [service was removed in 2021.12 of HA](https://github.com/home-assistant/core/pull/60537). The wled integration [now provides `number` entities for speed/intensity instead](https://www.home-assistant.io/integrations/wled/#number-entities). 

Example:
![image](https://user-images.githubusercontent.com/26947075/146837645-2e661814-d30f-49e6-b61a-3ef3bce450e8.png)

**Comment by randallspicher** [comment]
The Wiz api supports speed.  Just pass in the "speed" param (values 20-200)
 
`{
  "method": "setPilot",
  "params": {
    "speed": 190,
    "sceneId": 7
  }
}
`
https://docs.pro.wizconnected.com/?shell#graphql-schema is a pretty good reference. (the "cw" and "ww" args are just "c" and "w" when connecting directly to the bulb, but otherwise it's pretty useful)

**Comment by bdraco** [comment]
This can be closed as its implemented in the core version
