### ISSUE TITLE
Lights not showing up as devices

### ISSUE THREAD

**Issue by TravisRoy** [sbidy/wiz_light#39]
Home Assistant 0.115.6

Lights added with wiz_light integration are not showing up as devices so they can not be used in automation.

**Comment by steveothesane** [comment]
I was able to get them to work with the automation.  You have to call them as a service.  Once you do that they should operate as expected.

**Comment by TravisRoy** [comment]
> I was able to get them to work with the automation. You have to call them as a service. Once you do that they should operate as expected.

I guess that's an okay work around, but shouldn't they really show up as a device like all other lights?

**Comment by steveothesane** [comment]
I have noticed a lot of IoT devices don't appear like they should.  So I just play around with it until I get it to work.  I'm just thankful that someone did all the hard work of the re-engineering so that all I had to do was a little research and trial and error.  I still have a doorbell camera and a ceiling fan to figure out.  I'm loosing hair by the minute.  LOL

**Comment by TravisRoy** [comment]
@steveothesane Do you have an example of some automations with the Wiz bulbs? I can't seem to figure it out. I just want it to turn on when a motion sensor detects motion.

**Comment by steveothesane** [comment]
@TravisRoy absolutely.  So in Configurations then Automations, in the Actions section this is how I did it:
![image](https://user-images.githubusercontent.com/32602457/95496631-f4458900-0955-11eb-9a4b-6d20c06c9340.png)
Here is the code from the automations.yaml file:
- id: 'some number'
  alias: Light off just after sunrise
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: '15'
  condition: []
  action:
  - service: light.turn_off
    data: {}
    entity_id: light.porch_light
  - type: turn_off
    device_id: <some_random_jibberish>
    entity_id: switch.<some_random_jibberish>
    domain: switch
  mode: single
- id: '<some_number>'
  alias: Lights on just before sunset
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '-15'
  condition: []
  action:
  - service: light.turn_on
    data: {}
    entity_id: light.porch_light
  - type: turn_on
    device_id: <some_random_jibberish>
    entity_id: switch.<some_random_jibberish>
    domain: switch
  mode: single

Now I have two devices with actions here.  One is a outlet switch for a lamp without a smart bulb and the other is the Wiz bulb.  That would be the porch light.

Let me know how yours turns out.

**Comment by TravisRoy** [comment]
@steveothesane WOOHOO! That's exactly what I was looking for. Thank you so much.

**Comment by sbidy** [comment]
@steveothesane thank you for the support!

**Comment by steveothesane** [comment]
@TravisRoy &@sbidy you are very welcome.  We are a single community where each of us needs help that another can offer.
